"""
Coder Agent — เชี่ยวชาญการเขียนโค้ด
"""

from .base_agent import BaseAgent, AgentMessage
from typing import Dict, Optional


class CoderAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="coder",
            specialties=["coding", "debugging", "code_review", "architecture"],
            model_preference="openrouter-cohere-code",
        )
        self._code_history = []

    def on_message(self, msg: AgentMessage):
        if msg.topic == "code_request":
            result = self.work(msg.content, msg.data)
            self.send(to=msg.sender, topic="code_result", content=result, reply_to=msg.id)
        elif msg.topic == "review_request":
            result = self.review_code(msg.content)
            self.send(to=msg.sender, topic="review_result", content=result, reply_to=msg.id)

    def work(self, task: str, context: Dict = None) -> str:
        """เขียนโค้ดตาม task — ใช้ LLM จริง"""
        self._task_count += 1
        lang = (context or {}).get("language", "python")

        # Use real LLM
        prompt = f"Write {lang} code for: {task}. Return ONLY the code, no explanation."
        code = self.call_llm(prompt, task_type="coding")

        self._code_history.append({"task": task, "code": code})
        self.save_memory(
            f"code_{self._task_count}",
            {"task": task, "code": code, "lang": lang},
            tags=["code", lang],
        )

        return f"[Coder] Generated {lang} code:\n```{lang}\n{code}\n```"

    def _generate_code(self, task: str, lang: str) -> str:
        templates = {
            "python": f'# Generated by Coder Agent\n# Task: {task[:60]}\n\ndef solve():\n    """{task[:80]}"""\n    pass',
            "javascript": f'// Generated by Coder Agent\n// Task: {task[:60]}\n\nfunction solve() {{\n    // {task[:80]}\n}}',
        }
        return templates.get(lang, templates["python"])

    def review_code(self, code: str) -> str:
        issues = []
        if "TODO" in code:
            issues.append("Contains TODO comments")
        if "print(" in code and "debug" not in code.lower():
            issues.append("Contains print statements (remove in production)")
        if len(code.split("\n")) > 100:
            issues.append("Function too long, consider splitting")

        return f"[Coder Review] Found {len(issues)} issues:\n" + "\n".join(f"- {i}" for i in issues) if issues else "[Coder Review] Code looks clean ✅"

    def analyze_problem(self, problem: str) -> str:
        return (
            f"[Coder] มุมมองด้านเทคนิค:\n"
            f"- ต้องพิจารณา architecture\n"
            f"- ต้องเลือก data structures ที่เหมาะสม\n"
            f"- ต้อง考虑 scalability"
        )
